//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:47:08 PM CET 
//


package com.delices.datastore.jaxb.standings;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordType")
public class RecordType {

    @XmlAttribute(name = "wins", required = true)
    protected BigInteger wins;
    @XmlAttribute(name = "losses", required = true)
    protected BigInteger losses;
    @XmlAttribute(name = "overtime_losses")
    protected BigInteger overtimeLosses;
    @XmlAttribute(name = "win_pct", required = true)
    protected BigDecimal winPct;

    /**
     * Gets the value of the wins property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWins() {
        return wins;
    }

    /**
     * Sets the value of the wins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWins(BigInteger value) {
        this.wins = value;
    }

    /**
     * Gets the value of the losses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLosses() {
        return losses;
    }

    /**
     * Sets the value of the losses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLosses(BigInteger value) {
        this.losses = value;
    }

    /**
     * Gets the value of the overtimeLosses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOvertimeLosses() {
        return overtimeLosses;
    }

    /**
     * Sets the value of the overtimeLosses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOvertimeLosses(BigInteger value) {
        this.overtimeLosses = value;
    }

    /**
     * Gets the value of the winPct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWinPct() {
        return winPct;
    }

    /**
     * Sets the value of the winPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWinPct(BigDecimal value) {
        this.winPct = value;
    }

}
