//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:47:08 PM CET 
//


package com.delices.datastore.jaxb.standings;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for teamRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="teamRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="streak">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="loss" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}streakRecordType"/>
 *                   &lt;element name="win" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}streakRecordType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="records">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="atlantic" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="central" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="conference" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="division" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="home" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="last_10" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="last_10_home" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="last_10_road" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="northeast" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="northwest" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="pacific" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="road" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="southeast" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="metro" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                   &lt;element name="metropolitan" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}baseTeamAttributes"/>
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordAttributes"/>
 *       &lt;attribute name="games_played" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="points" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="regulation_wins" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="shootout_wins" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="shootout_losses" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="goals_for" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="goals_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="goal_diff" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="powerplays" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="powerplay_goals" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="powerplay_pct" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="powerplays_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="powerplay_goals_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="penalty_killing_pct" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "teamRecordType", propOrder = {
    "streak",
    "records"
})
public class TeamRecordType {

    @XmlElement(required = true)
    protected TeamRecordType.Streak streak;
    @XmlElement(required = true)
    protected TeamRecordType.Records records;
    @XmlAttribute(name = "games_played")
    protected BigInteger gamesPlayed;
    @XmlAttribute(name = "points")
    protected BigInteger points;
    @XmlAttribute(name = "regulation_wins")
    protected BigInteger regulationWins;
    @XmlAttribute(name = "shootout_wins")
    protected BigInteger shootoutWins;
    @XmlAttribute(name = "shootout_losses")
    protected BigInteger shootoutLosses;
    @XmlAttribute(name = "goals_for")
    protected BigInteger goalsFor;
    @XmlAttribute(name = "goals_against")
    protected BigInteger goalsAgainst;
    @XmlAttribute(name = "goal_diff")
    protected BigInteger goalDiff;
    @XmlAttribute(name = "powerplays")
    protected BigInteger powerplays;
    @XmlAttribute(name = "powerplay_goals")
    protected BigInteger powerplayGoals;
    @XmlAttribute(name = "powerplay_pct")
    protected BigDecimal powerplayPct;
    @XmlAttribute(name = "powerplays_against")
    protected BigInteger powerplaysAgainst;
    @XmlAttribute(name = "powerplay_goals_against")
    protected BigInteger powerplayGoalsAgainst;
    @XmlAttribute(name = "penalty_killing_pct")
    protected BigDecimal penaltyKillingPct;
    @XmlAttribute(name = "market")
    protected String market;
    @XmlAttribute(name = "founded")
    protected BigInteger founded;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "alias")
    protected String alias;
    @XmlAttribute(name = "wins", required = true)
    protected BigInteger wins;
    @XmlAttribute(name = "losses", required = true)
    protected BigInteger losses;
    @XmlAttribute(name = "overtime_losses")
    protected BigInteger overtimeLosses;
    @XmlAttribute(name = "win_pct", required = true)
    protected BigDecimal winPct;

    /**
     * Gets the value of the streak property.
     * 
     * @return
     *     possible object is
     *     {@link TeamRecordType.Streak }
     *     
     */
    public TeamRecordType.Streak getStreak() {
        return streak;
    }

    /**
     * Sets the value of the streak property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamRecordType.Streak }
     *     
     */
    public void setStreak(TeamRecordType.Streak value) {
        this.streak = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link TeamRecordType.Records }
     *     
     */
    public TeamRecordType.Records getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamRecordType.Records }
     *     
     */
    public void setRecords(TeamRecordType.Records value) {
        this.records = value;
    }

    /**
     * Gets the value of the gamesPlayed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGamesPlayed() {
        return gamesPlayed;
    }

    /**
     * Sets the value of the gamesPlayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGamesPlayed(BigInteger value) {
        this.gamesPlayed = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPoints(BigInteger value) {
        this.points = value;
    }

    /**
     * Gets the value of the regulationWins property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRegulationWins() {
        return regulationWins;
    }

    /**
     * Sets the value of the regulationWins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRegulationWins(BigInteger value) {
        this.regulationWins = value;
    }

    /**
     * Gets the value of the shootoutWins property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShootoutWins() {
        return shootoutWins;
    }

    /**
     * Sets the value of the shootoutWins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShootoutWins(BigInteger value) {
        this.shootoutWins = value;
    }

    /**
     * Gets the value of the shootoutLosses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShootoutLosses() {
        return shootoutLosses;
    }

    /**
     * Sets the value of the shootoutLosses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShootoutLosses(BigInteger value) {
        this.shootoutLosses = value;
    }

    /**
     * Gets the value of the goalsFor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGoalsFor() {
        return goalsFor;
    }

    /**
     * Sets the value of the goalsFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGoalsFor(BigInteger value) {
        this.goalsFor = value;
    }

    /**
     * Gets the value of the goalsAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGoalsAgainst() {
        return goalsAgainst;
    }

    /**
     * Sets the value of the goalsAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGoalsAgainst(BigInteger value) {
        this.goalsAgainst = value;
    }

    /**
     * Gets the value of the goalDiff property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGoalDiff() {
        return goalDiff;
    }

    /**
     * Sets the value of the goalDiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGoalDiff(BigInteger value) {
        this.goalDiff = value;
    }

    /**
     * Gets the value of the powerplays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPowerplays() {
        return powerplays;
    }

    /**
     * Sets the value of the powerplays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPowerplays(BigInteger value) {
        this.powerplays = value;
    }

    /**
     * Gets the value of the powerplayGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPowerplayGoals() {
        return powerplayGoals;
    }

    /**
     * Sets the value of the powerplayGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPowerplayGoals(BigInteger value) {
        this.powerplayGoals = value;
    }

    /**
     * Gets the value of the powerplayPct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPowerplayPct() {
        return powerplayPct;
    }

    /**
     * Sets the value of the powerplayPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPowerplayPct(BigDecimal value) {
        this.powerplayPct = value;
    }

    /**
     * Gets the value of the powerplaysAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPowerplaysAgainst() {
        return powerplaysAgainst;
    }

    /**
     * Sets the value of the powerplaysAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPowerplaysAgainst(BigInteger value) {
        this.powerplaysAgainst = value;
    }

    /**
     * Gets the value of the powerplayGoalsAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPowerplayGoalsAgainst() {
        return powerplayGoalsAgainst;
    }

    /**
     * Sets the value of the powerplayGoalsAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPowerplayGoalsAgainst(BigInteger value) {
        this.powerplayGoalsAgainst = value;
    }

    /**
     * Gets the value of the penaltyKillingPct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPenaltyKillingPct() {
        return penaltyKillingPct;
    }

    /**
     * Sets the value of the penaltyKillingPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPenaltyKillingPct(BigDecimal value) {
        this.penaltyKillingPct = value;
    }

    /**
     * Gets the value of the market property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarket() {
        return market;
    }

    /**
     * Sets the value of the market property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarket(String value) {
        this.market = value;
    }

    /**
     * Gets the value of the founded property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFounded() {
        return founded;
    }

    /**
     * Sets the value of the founded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFounded(BigInteger value) {
        this.founded = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the wins property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWins() {
        return wins;
    }

    /**
     * Sets the value of the wins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWins(BigInteger value) {
        this.wins = value;
    }

    /**
     * Gets the value of the losses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLosses() {
        return losses;
    }

    /**
     * Sets the value of the losses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLosses(BigInteger value) {
        this.losses = value;
    }

    /**
     * Gets the value of the overtimeLosses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOvertimeLosses() {
        return overtimeLosses;
    }

    /**
     * Sets the value of the overtimeLosses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOvertimeLosses(BigInteger value) {
        this.overtimeLosses = value;
    }

    /**
     * Gets the value of the winPct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWinPct() {
        return winPct;
    }

    /**
     * Sets the value of the winPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWinPct(BigDecimal value) {
        this.winPct = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="atlantic" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="central" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="conference" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="division" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="home" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="last_10" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="last_10_home" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="last_10_road" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="northeast" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="northwest" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="pacific" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="road" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="southeast" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="metro" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *         &lt;element name="metropolitan" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}recordType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "atlanticOrCentralOrConference"
    })
    public static class Records {

        @XmlElementRefs({
            @XmlElementRef(name = "northwest", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "southeast", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "central", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "division", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "atlantic", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "last_10", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "metro", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "conference", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "northeast", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "pacific", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "home", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "last_10_road", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "metropolitan", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "last_10_home", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "road", namespace = "http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<RecordType>> atlanticOrCentralOrConference;

        /**
         * Gets the value of the atlanticOrCentralOrConference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the atlanticOrCentralOrConference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAtlanticOrCentralOrConference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * {@link JAXBElement }{@code <}{@link RecordType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<RecordType>> getAtlanticOrCentralOrConference() {
            if (atlanticOrCentralOrConference == null) {
                atlanticOrCentralOrConference = new ArrayList<JAXBElement<RecordType>>();
            }
            return this.atlanticOrCentralOrConference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="loss" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}streakRecordType"/>
     *         &lt;element name="win" type="{http://feed.elasticstats.com/schema/hockey/nhl/standings-v2.0.xsd}streakRecordType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "loss",
        "win"
    })
    public static class Streak {

        protected StreakRecordType loss;
        protected StreakRecordType win;

        /**
         * Gets the value of the loss property.
         * 
         * @return
         *     possible object is
         *     {@link StreakRecordType }
         *     
         */
        public StreakRecordType getLoss() {
            return loss;
        }

        /**
         * Sets the value of the loss property.
         * 
         * @param value
         *     allowed object is
         *     {@link StreakRecordType }
         *     
         */
        public void setLoss(StreakRecordType value) {
            this.loss = value;
        }

        /**
         * Gets the value of the win property.
         * 
         * @return
         *     possible object is
         *     {@link StreakRecordType }
         *     
         */
        public StreakRecordType getWin() {
            return win;
        }

        /**
         * Sets the value of the win property.
         * 
         * @param value
         *     allowed object is
         *     {@link StreakRecordType }
         *     
         */
        public void setWin(StreakRecordType value) {
            this.win = value;
        }

    }

}
