//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:46:01 PM CET 
//


package com.delices.datastore.jaxb.changelog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for leagueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leagueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="changelog">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="profiles">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="teams" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}teamEntryType" minOccurs="0"/>
 *                             &lt;element name="players" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}playerEntryType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="games">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="schedule" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}gameEntryType" minOccurs="0"/>
 *                             &lt;element name="results" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}gameEntryType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="standings" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}teamEntryType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="end_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="start_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}baseOrganizationAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leagueType", propOrder = {
    "changelog"
})
public class LeagueType {

    @XmlElement(required = true)
    protected LeagueType.Changelog changelog;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "alias")
    protected String alias;

    /**
     * Gets the value of the changelog property.
     * 
     * @return
     *     possible object is
     *     {@link LeagueType.Changelog }
     *     
     */
    public LeagueType.Changelog getChangelog() {
        return changelog;
    }

    /**
     * Sets the value of the changelog property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeagueType.Changelog }
     *     
     */
    public void setChangelog(LeagueType.Changelog value) {
        this.changelog = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="profiles">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="teams" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}teamEntryType" minOccurs="0"/>
     *                   &lt;element name="players" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}playerEntryType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="games">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="schedule" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}gameEntryType" minOccurs="0"/>
     *                   &lt;element name="results" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}gameEntryType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="standings" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}teamEntryType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="end_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="start_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "profiles",
        "games",
        "standings"
    })
    public static class Changelog {

        @XmlElement(required = true)
        protected LeagueType.Changelog.Profiles profiles;
        @XmlElement(required = true)
        protected LeagueType.Changelog.Games games;
        protected TeamEntryType standings;
        @XmlAttribute(name = "end_time", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar endTime;
        @XmlAttribute(name = "start_time", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar startTime;

        /**
         * Gets the value of the profiles property.
         * 
         * @return
         *     possible object is
         *     {@link LeagueType.Changelog.Profiles }
         *     
         */
        public LeagueType.Changelog.Profiles getProfiles() {
            return profiles;
        }

        /**
         * Sets the value of the profiles property.
         * 
         * @param value
         *     allowed object is
         *     {@link LeagueType.Changelog.Profiles }
         *     
         */
        public void setProfiles(LeagueType.Changelog.Profiles value) {
            this.profiles = value;
        }

        /**
         * Gets the value of the games property.
         * 
         * @return
         *     possible object is
         *     {@link LeagueType.Changelog.Games }
         *     
         */
        public LeagueType.Changelog.Games getGames() {
            return games;
        }

        /**
         * Sets the value of the games property.
         * 
         * @param value
         *     allowed object is
         *     {@link LeagueType.Changelog.Games }
         *     
         */
        public void setGames(LeagueType.Changelog.Games value) {
            this.games = value;
        }

        /**
         * Gets the value of the standings property.
         * 
         * @return
         *     possible object is
         *     {@link TeamEntryType }
         *     
         */
        public TeamEntryType getStandings() {
            return standings;
        }

        /**
         * Sets the value of the standings property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamEntryType }
         *     
         */
        public void setStandings(TeamEntryType value) {
            this.standings = value;
        }

        /**
         * Gets the value of the endTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndTime() {
            return endTime;
        }

        /**
         * Sets the value of the endTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndTime(XMLGregorianCalendar value) {
            this.endTime = value;
        }

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartTime(XMLGregorianCalendar value) {
            this.startTime = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="schedule" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}gameEntryType" minOccurs="0"/>
         *         &lt;element name="results" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}gameEntryType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "schedule",
            "results"
        })
        public static class Games {

            protected GameEntryType schedule;
            protected GameEntryType results;

            /**
             * Gets the value of the schedule property.
             * 
             * @return
             *     possible object is
             *     {@link GameEntryType }
             *     
             */
            public GameEntryType getSchedule() {
                return schedule;
            }

            /**
             * Sets the value of the schedule property.
             * 
             * @param value
             *     allowed object is
             *     {@link GameEntryType }
             *     
             */
            public void setSchedule(GameEntryType value) {
                this.schedule = value;
            }

            /**
             * Gets the value of the results property.
             * 
             * @return
             *     possible object is
             *     {@link GameEntryType }
             *     
             */
            public GameEntryType getResults() {
                return results;
            }

            /**
             * Sets the value of the results property.
             * 
             * @param value
             *     allowed object is
             *     {@link GameEntryType }
             *     
             */
            public void setResults(GameEntryType value) {
                this.results = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="teams" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}teamEntryType" minOccurs="0"/>
         *         &lt;element name="players" type="{http://feed.elasticstats.com/schema/hockey/changelog-v2.0.xsd}playerEntryType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "teams",
            "players"
        })
        public static class Profiles {

            protected TeamEntryType teams;
            protected PlayerEntryType players;

            /**
             * Gets the value of the teams property.
             * 
             * @return
             *     possible object is
             *     {@link TeamEntryType }
             *     
             */
            public TeamEntryType getTeams() {
                return teams;
            }

            /**
             * Sets the value of the teams property.
             * 
             * @param value
             *     allowed object is
             *     {@link TeamEntryType }
             *     
             */
            public void setTeams(TeamEntryType value) {
                this.teams = value;
            }

            /**
             * Gets the value of the players property.
             * 
             * @return
             *     possible object is
             *     {@link PlayerEntryType }
             *     
             */
            public PlayerEntryType getPlayers() {
                return players;
            }

            /**
             * Sets the value of the players property.
             * 
             * @param value
             *     allowed object is
             *     {@link PlayerEntryType }
             *     
             */
            public void setPlayers(PlayerEntryType value) {
                this.players = value;
            }

        }

    }

}
