//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:45:48 PM CET 
//


package com.delices.datastore.jaxb.game;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for goaltendingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="goaltendingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/game-v2.0.xsd}baseGoaltendingAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "goaltendingType")
public class GoaltendingType {

    @XmlAttribute(name = "saves")
    protected BigInteger saves;
    @XmlAttribute(name = "saves_pct")
    protected BigDecimal savesPct;
    @XmlAttribute(name = "shots_against")
    protected BigInteger shotsAgainst;
    @XmlAttribute(name = "goals_against")
    protected BigInteger goalsAgainst;

    /**
     * Gets the value of the saves property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSaves() {
        return saves;
    }

    /**
     * Sets the value of the saves property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSaves(BigInteger value) {
        this.saves = value;
    }

    /**
     * Gets the value of the savesPct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSavesPct() {
        return savesPct;
    }

    /**
     * Sets the value of the savesPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSavesPct(BigDecimal value) {
        this.savesPct = value;
    }

    /**
     * Gets the value of the shotsAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShotsAgainst() {
        return shotsAgainst;
    }

    /**
     * Sets the value of the shotsAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShotsAgainst(BigInteger value) {
        this.shotsAgainst = value;
    }

    /**
     * Gets the value of the goalsAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGoalsAgainst() {
        return goalsAgainst;
    }

    /**
     * Sets the value of the goalsAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGoalsAgainst(BigInteger value) {
        this.goalsAgainst = value;
    }

}
