//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:45:48 PM CET 
//


package com.delices.datastore.jaxb.game;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for periodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="periodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/game-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *         &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/game-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *         &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/game-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *         &lt;element name="penalty" type="{http://feed.elasticstats.com/schema/hockey/game-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/game-v2.0.xsd}baseGoaltendingAttributes"/>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="REG"/>
 *             &lt;enumeration value="OT"/>
 *             &lt;enumeration value="SO"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "periodType", propOrder = {
    "powerplay",
    "shorthanded",
    "evenstrength",
    "penalty"
})
public class PeriodType {

    protected GoaltendingType powerplay;
    protected GoaltendingType shorthanded;
    protected GoaltendingType evenstrength;
    protected GoaltendingType penalty;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "number", required = true)
    protected BigInteger number;
    @XmlAttribute(name = "sequence", required = true)
    protected BigInteger sequence;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "saves")
    protected BigInteger saves;
    @XmlAttribute(name = "saves_pct")
    protected BigDecimal savesPct;
    @XmlAttribute(name = "shots_against")
    protected BigInteger shotsAgainst;
    @XmlAttribute(name = "goals_against")
    protected BigInteger goalsAgainst;

    /**
     * Gets the value of the powerplay property.
     * 
     * @return
     *     possible object is
     *     {@link GoaltendingType }
     *     
     */
    public GoaltendingType getPowerplay() {
        return powerplay;
    }

    /**
     * Sets the value of the powerplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoaltendingType }
     *     
     */
    public void setPowerplay(GoaltendingType value) {
        this.powerplay = value;
    }

    /**
     * Gets the value of the shorthanded property.
     * 
     * @return
     *     possible object is
     *     {@link GoaltendingType }
     *     
     */
    public GoaltendingType getShorthanded() {
        return shorthanded;
    }

    /**
     * Sets the value of the shorthanded property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoaltendingType }
     *     
     */
    public void setShorthanded(GoaltendingType value) {
        this.shorthanded = value;
    }

    /**
     * Gets the value of the evenstrength property.
     * 
     * @return
     *     possible object is
     *     {@link GoaltendingType }
     *     
     */
    public GoaltendingType getEvenstrength() {
        return evenstrength;
    }

    /**
     * Sets the value of the evenstrength property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoaltendingType }
     *     
     */
    public void setEvenstrength(GoaltendingType value) {
        this.evenstrength = value;
    }

    /**
     * Gets the value of the penalty property.
     * 
     * @return
     *     possible object is
     *     {@link GoaltendingType }
     *     
     */
    public GoaltendingType getPenalty() {
        return penalty;
    }

    /**
     * Sets the value of the penalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoaltendingType }
     *     
     */
    public void setPenalty(GoaltendingType value) {
        this.penalty = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the saves property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSaves() {
        return saves;
    }

    /**
     * Sets the value of the saves property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSaves(BigInteger value) {
        this.saves = value;
    }

    /**
     * Gets the value of the savesPct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSavesPct() {
        return savesPct;
    }

    /**
     * Sets the value of the savesPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSavesPct(BigDecimal value) {
        this.savesPct = value;
    }

    /**
     * Gets the value of the shotsAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShotsAgainst() {
        return shotsAgainst;
    }

    /**
     * Sets the value of the shotsAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShotsAgainst(BigInteger value) {
        this.shotsAgainst = value;
    }

    /**
     * Gets the value of the goalsAgainst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGoalsAgainst() {
        return goalsAgainst;
    }

    /**
     * Sets the value of the goalsAgainst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGoalsAgainst(BigInteger value) {
        this.goalsAgainst = value;
    }

}
