//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:47:18 PM CET 
//


package com.delices.datastore.jaxb.statistics;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.delices.datastore.jaxb.statistics package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Series_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd", "series");
    private final static QName _Season_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd", "season");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.delices.datastore.jaxb.statistics
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TeamType }
     * 
     */
    public TeamType createTeamType() {
        return new TeamType();
    }

    /**
     * Create an instance of {@link TeamType.PlayerRecords }
     * 
     */
    public TeamType.PlayerRecords createTeamTypePlayerRecords() {
        return new TeamType.PlayerRecords();
    }

    /**
     * Create an instance of {@link PlayerRecordType }
     * 
     */
    public PlayerRecordType createPlayerRecordType() {
        return new PlayerRecordType();
    }

    /**
     * Create an instance of {@link PlayerRecordType.Goaltending }
     * 
     */
    public PlayerRecordType.Goaltending createPlayerRecordTypeGoaltending() {
        return new PlayerRecordType.Goaltending();
    }

    /**
     * Create an instance of {@link PlayerRecordType.TimeOnIce }
     * 
     */
    public PlayerRecordType.TimeOnIce createPlayerRecordTypeTimeOnIce() {
        return new PlayerRecordType.TimeOnIce();
    }

    /**
     * Create an instance of {@link PlayerRecordType.Statistics }
     * 
     */
    public PlayerRecordType.Statistics createPlayerRecordTypeStatistics() {
        return new PlayerRecordType.Statistics();
    }

    /**
     * Create an instance of {@link TeamRecordType }
     * 
     */
    public TeamRecordType createTeamRecordType() {
        return new TeamRecordType();
    }

    /**
     * Create an instance of {@link TeamRecordType.Goaltending }
     * 
     */
    public TeamRecordType.Goaltending createTeamRecordTypeGoaltending() {
        return new TeamRecordType.Goaltending();
    }

    /**
     * Create an instance of {@link TeamRecordType.Statistics }
     * 
     */
    public TeamRecordType.Statistics createTeamRecordTypeStatistics() {
        return new TeamRecordType.Statistics();
    }

    /**
     * Create an instance of {@link TeamRecordType.Statistics.Total }
     * 
     */
    public TeamRecordType.Statistics.Total createTeamRecordTypeStatisticsTotal() {
        return new TeamRecordType.Statistics.Total();
    }

    /**
     * Create an instance of {@link SeriesType }
     * 
     */
    public SeriesType createSeriesType() {
        return new SeriesType();
    }

    /**
     * Create an instance of {@link SeasonType }
     * 
     */
    public SeasonType createSeasonType() {
        return new SeasonType();
    }

    /**
     * Create an instance of {@link ShootingType }
     * 
     */
    public ShootingType createShootingType() {
        return new ShootingType();
    }

    /**
     * Create an instance of {@link GoaltendingType }
     * 
     */
    public GoaltendingType createGoaltendingType() {
        return new GoaltendingType();
    }

    /**
     * Create an instance of {@link DraftType }
     * 
     */
    public DraftType createDraftType() {
        return new DraftType();
    }

    /**
     * Create an instance of {@link VenueType }
     * 
     */
    public VenueType createVenueType() {
        return new VenueType();
    }

    /**
     * Create an instance of {@link ScoringType }
     * 
     */
    public ScoringType createScoringType() {
        return new ScoringType();
    }

    /**
     * Create an instance of {@link NetType }
     * 
     */
    public NetType createNetType() {
        return new NetType();
    }

    /**
     * Create an instance of {@link TimeOnIceType }
     * 
     */
    public TimeOnIceType createTimeOnIceType() {
        return new TimeOnIceType();
    }

    /**
     * Create an instance of {@link InjuryType }
     * 
     */
    public InjuryType createInjuryType() {
        return new InjuryType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link TeamType.TeamRecords }
     * 
     */
    public TeamType.TeamRecords createTeamTypeTeamRecords() {
        return new TeamType.TeamRecords();
    }

    /**
     * Create an instance of {@link TeamType.PlayerRecords.Player }
     * 
     */
    public TeamType.PlayerRecords.Player createTeamTypePlayerRecordsPlayer() {
        return new TeamType.PlayerRecords.Player();
    }

    /**
     * Create an instance of {@link PlayerRecordType.Goaltending.Total }
     * 
     */
    public PlayerRecordType.Goaltending.Total createPlayerRecordTypeGoaltendingTotal() {
        return new PlayerRecordType.Goaltending.Total();
    }

    /**
     * Create an instance of {@link PlayerRecordType.Goaltending.Average }
     * 
     */
    public PlayerRecordType.Goaltending.Average createPlayerRecordTypeGoaltendingAverage() {
        return new PlayerRecordType.Goaltending.Average();
    }

    /**
     * Create an instance of {@link PlayerRecordType.TimeOnIce.Total }
     * 
     */
    public PlayerRecordType.TimeOnIce.Total createPlayerRecordTypeTimeOnIceTotal() {
        return new PlayerRecordType.TimeOnIce.Total();
    }

    /**
     * Create an instance of {@link PlayerRecordType.TimeOnIce.Average }
     * 
     */
    public PlayerRecordType.TimeOnIce.Average createPlayerRecordTypeTimeOnIceAverage() {
        return new PlayerRecordType.TimeOnIce.Average();
    }

    /**
     * Create an instance of {@link PlayerRecordType.Statistics.Total }
     * 
     */
    public PlayerRecordType.Statistics.Total createPlayerRecordTypeStatisticsTotal() {
        return new PlayerRecordType.Statistics.Total();
    }

    /**
     * Create an instance of {@link PlayerRecordType.Statistics.Average }
     * 
     */
    public PlayerRecordType.Statistics.Average createPlayerRecordTypeStatisticsAverage() {
        return new PlayerRecordType.Statistics.Average();
    }

    /**
     * Create an instance of {@link TeamRecordType.Shootout }
     * 
     */
    public TeamRecordType.Shootout createTeamRecordTypeShootout() {
        return new TeamRecordType.Shootout();
    }

    /**
     * Create an instance of {@link TeamRecordType.Goaltending.Total }
     * 
     */
    public TeamRecordType.Goaltending.Total createTeamRecordTypeGoaltendingTotal() {
        return new TeamRecordType.Goaltending.Total();
    }

    /**
     * Create an instance of {@link TeamRecordType.Goaltending.Average }
     * 
     */
    public TeamRecordType.Goaltending.Average createTeamRecordTypeGoaltendingAverage() {
        return new TeamRecordType.Goaltending.Average();
    }

    /**
     * Create an instance of {@link TeamRecordType.Goaltending.Emptynet }
     * 
     */
    public TeamRecordType.Goaltending.Emptynet createTeamRecordTypeGoaltendingEmptynet() {
        return new TeamRecordType.Goaltending.Emptynet();
    }

    /**
     * Create an instance of {@link TeamRecordType.Statistics.Average }
     * 
     */
    public TeamRecordType.Statistics.Average createTeamRecordTypeStatisticsAverage() {
        return new TeamRecordType.Statistics.Average();
    }

    /**
     * Create an instance of {@link TeamRecordType.Statistics.Total.Penalty }
     * 
     */
    public TeamRecordType.Statistics.Total.Penalty createTeamRecordTypeStatisticsTotalPenalty() {
        return new TeamRecordType.Statistics.Total.Penalty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd", name = "series")
    public JAXBElement<SeriesType> createSeries(SeriesType value) {
        return new JAXBElement<SeriesType>(_Series_QNAME, SeriesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeasonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd", name = "season")
    public JAXBElement<SeasonType> createSeason(SeasonType value) {
        return new JAXBElement<SeasonType>(_Season_QNAME, SeasonType.class, null, value);
    }

}
