//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:47:18 PM CET 
//


package com.delices.datastore.jaxb.statistics;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for teamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="teamType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="team_records" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="overall" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}teamRecordType" minOccurs="0"/>
 *                   &lt;element name="opponents" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}teamRecordType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="player_records" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="player" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}playerRecordType">
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}basePlayerAttributes"/>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseTeamAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "teamType", propOrder = {
    "teamRecords",
    "playerRecords"
})
public class TeamType {

    @XmlElement(name = "team_records")
    protected TeamType.TeamRecords teamRecords;
    @XmlElement(name = "player_records")
    protected TeamType.PlayerRecords playerRecords;
    @XmlAttribute(name = "market")
    protected String market;
    @XmlAttribute(name = "founded")
    protected BigInteger founded;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "alias")
    protected String alias;

    /**
     * Gets the value of the teamRecords property.
     * 
     * @return
     *     possible object is
     *     {@link TeamType.TeamRecords }
     *     
     */
    public TeamType.TeamRecords getTeamRecords() {
        return teamRecords;
    }

    /**
     * Sets the value of the teamRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamType.TeamRecords }
     *     
     */
    public void setTeamRecords(TeamType.TeamRecords value) {
        this.teamRecords = value;
    }

    /**
     * Gets the value of the playerRecords property.
     * 
     * @return
     *     possible object is
     *     {@link TeamType.PlayerRecords }
     *     
     */
    public TeamType.PlayerRecords getPlayerRecords() {
        return playerRecords;
    }

    /**
     * Sets the value of the playerRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamType.PlayerRecords }
     *     
     */
    public void setPlayerRecords(TeamType.PlayerRecords value) {
        this.playerRecords = value;
    }

    /**
     * Gets the value of the market property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarket() {
        return market;
    }

    /**
     * Sets the value of the market property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarket(String value) {
        this.market = value;
    }

    /**
     * Gets the value of the founded property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFounded() {
        return founded;
    }

    /**
     * Sets the value of the founded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFounded(BigInteger value) {
        this.founded = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="player" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}playerRecordType">
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}basePlayerAttributes"/>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "player"
    })
    public static class PlayerRecords {

        protected List<TeamType.PlayerRecords.Player> player;

        /**
         * Gets the value of the player property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the player property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlayer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TeamType.PlayerRecords.Player }
         * 
         * 
         */
        public List<TeamType.PlayerRecords.Player> getPlayer() {
            if (player == null) {
                player = new ArrayList<TeamType.PlayerRecords.Player>();
            }
            return this.player;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}playerRecordType">
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}basePlayerAttributes"/>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Player
            extends PlayerRecordType
        {

            @XmlAttribute(name = "abbr_name")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String abbrName;
            @XmlAttribute(name = "jersey_number")
            protected String jerseyNumber;
            @XmlAttribute(name = "position")
            protected PositionType position;
            @XmlAttribute(name = "primary_position")
            protected PositionType primaryPosition;
            @XmlAttribute(name = "status")
            protected String status;
            @XmlAttribute(name = "handedness")
            protected String handedness;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "first_name")
            protected String firstName;
            @XmlAttribute(name = "last_name")
            protected String lastName;
            @XmlAttribute(name = "full_name")
            protected String fullName;

            /**
             * Gets the value of the abbrName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbbrName() {
                return abbrName;
            }

            /**
             * Sets the value of the abbrName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbbrName(String value) {
                this.abbrName = value;
            }

            /**
             * Gets the value of the jerseyNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJerseyNumber() {
                return jerseyNumber;
            }

            /**
             * Sets the value of the jerseyNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJerseyNumber(String value) {
                this.jerseyNumber = value;
            }

            /**
             * Gets the value of the position property.
             * 
             * @return
             *     possible object is
             *     {@link PositionType }
             *     
             */
            public PositionType getPosition() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             * @param value
             *     allowed object is
             *     {@link PositionType }
             *     
             */
            public void setPosition(PositionType value) {
                this.position = value;
            }

            /**
             * Gets the value of the primaryPosition property.
             * 
             * @return
             *     possible object is
             *     {@link PositionType }
             *     
             */
            public PositionType getPrimaryPosition() {
                return primaryPosition;
            }

            /**
             * Sets the value of the primaryPosition property.
             * 
             * @param value
             *     allowed object is
             *     {@link PositionType }
             *     
             */
            public void setPrimaryPosition(PositionType value) {
                this.primaryPosition = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the handedness property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHandedness() {
                return handedness;
            }

            /**
             * Sets the value of the handedness property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHandedness(String value) {
                this.handedness = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the firstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

            /**
             * Gets the value of the lastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastName() {
                return lastName;
            }

            /**
             * Sets the value of the lastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastName(String value) {
                this.lastName = value;
            }

            /**
             * Gets the value of the fullName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullName() {
                return fullName;
            }

            /**
             * Sets the value of the fullName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullName(String value) {
                this.fullName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="overall" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}teamRecordType" minOccurs="0"/>
     *         &lt;element name="opponents" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}teamRecordType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "overall",
        "opponents"
    })
    public static class TeamRecords {

        protected TeamRecordType overall;
        protected TeamRecordType opponents;

        /**
         * Gets the value of the overall property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType }
         *     
         */
        public TeamRecordType getOverall() {
            return overall;
        }

        /**
         * Sets the value of the overall property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType }
         *     
         */
        public void setOverall(TeamRecordType value) {
            this.overall = value;
        }

        /**
         * Gets the value of the opponents property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType }
         *     
         */
        public TeamRecordType getOpponents() {
            return opponents;
        }

        /**
         * Sets the value of the opponents property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType }
         *     
         */
        public void setOpponents(TeamRecordType value) {
            this.opponents = value;
        }

    }

}
