//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:47:18 PM CET 
//


package com.delices.datastore.jaxb.statistics;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for teamRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="teamRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statistics" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="total" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
 *                             &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
 *                             &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
 *                             &lt;element name="penalty" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseShootingAttributes"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}faceoffAttributes"/>
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseSkaterAttributes"/>
 *                           &lt;attribute name="games_played" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="powerplays" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="team_penalties" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="team_penalty_minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="average" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseAverageSkaterAttributes"/>
 *                           &lt;attribute name="team_penalties" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="team_penalty_minutes" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shootout" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseGoaltendingAttributes"/>
 *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseShootingAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="goaltending" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="total" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *                             &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *                             &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *                             &lt;element name="penalty" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseGoaltendingAttributes"/>
 *                           &lt;attribute name="total_shots_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="total_goals_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="average" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseAverageGoaltendingAttributes"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="emptynet" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
 *                             &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
 *                             &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseNetAttributes"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "teamRecordType", propOrder = {
    "statistics",
    "shootout",
    "goaltending"
})
public class TeamRecordType {

    protected TeamRecordType.Statistics statistics;
    protected TeamRecordType.Shootout shootout;
    protected TeamRecordType.Goaltending goaltending;

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link TeamRecordType.Statistics }
     *     
     */
    public TeamRecordType.Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamRecordType.Statistics }
     *     
     */
    public void setStatistics(TeamRecordType.Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the shootout property.
     * 
     * @return
     *     possible object is
     *     {@link TeamRecordType.Shootout }
     *     
     */
    public TeamRecordType.Shootout getShootout() {
        return shootout;
    }

    /**
     * Sets the value of the shootout property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamRecordType.Shootout }
     *     
     */
    public void setShootout(TeamRecordType.Shootout value) {
        this.shootout = value;
    }

    /**
     * Gets the value of the goaltending property.
     * 
     * @return
     *     possible object is
     *     {@link TeamRecordType.Goaltending }
     *     
     */
    public TeamRecordType.Goaltending getGoaltending() {
        return goaltending;
    }

    /**
     * Sets the value of the goaltending property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamRecordType.Goaltending }
     *     
     */
    public void setGoaltending(TeamRecordType.Goaltending value) {
        this.goaltending = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="total" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
     *                   &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
     *                   &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
     *                   &lt;element name="penalty" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseGoaltendingAttributes"/>
     *                 &lt;attribute name="total_shots_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="total_goals_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="average" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseAverageGoaltendingAttributes"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="emptynet" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
     *                   &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
     *                   &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseNetAttributes"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "total",
        "average",
        "emptynet"
    })
    public static class Goaltending {

        protected TeamRecordType.Goaltending.Total total;
        protected TeamRecordType.Goaltending.Average average;
        protected TeamRecordType.Goaltending.Emptynet emptynet;

        /**
         * Gets the value of the total property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType.Goaltending.Total }
         *     
         */
        public TeamRecordType.Goaltending.Total getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType.Goaltending.Total }
         *     
         */
        public void setTotal(TeamRecordType.Goaltending.Total value) {
            this.total = value;
        }

        /**
         * Gets the value of the average property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType.Goaltending.Average }
         *     
         */
        public TeamRecordType.Goaltending.Average getAverage() {
            return average;
        }

        /**
         * Sets the value of the average property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType.Goaltending.Average }
         *     
         */
        public void setAverage(TeamRecordType.Goaltending.Average value) {
            this.average = value;
        }

        /**
         * Gets the value of the emptynet property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType.Goaltending.Emptynet }
         *     
         */
        public TeamRecordType.Goaltending.Emptynet getEmptynet() {
            return emptynet;
        }

        /**
         * Sets the value of the emptynet property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType.Goaltending.Emptynet }
         *     
         */
        public void setEmptynet(TeamRecordType.Goaltending.Emptynet value) {
            this.emptynet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseAverageGoaltendingAttributes"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Average {

            @XmlAttribute(name = "goals_against")
            protected BigDecimal goalsAgainst;
            @XmlAttribute(name = "shots_against")
            protected BigDecimal shotsAgainst;

            /**
             * Gets the value of the goalsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getGoalsAgainst() {
                return goalsAgainst;
            }

            /**
             * Sets the value of the goalsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setGoalsAgainst(BigDecimal value) {
                this.goalsAgainst = value;
            }

            /**
             * Gets the value of the shotsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getShotsAgainst() {
                return shotsAgainst;
            }

            /**
             * Sets the value of the shotsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setShotsAgainst(BigDecimal value) {
                this.shotsAgainst = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
         *         &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
         *         &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}netType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseNetAttributes"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "powerplay",
            "shorthanded",
            "evenstrength"
        })
        public static class Emptynet {

            protected NetType powerplay;
            protected NetType shorthanded;
            protected NetType evenstrength;
            @XmlAttribute(name = "shots_against")
            protected BigInteger shotsAgainst;
            @XmlAttribute(name = "goals_against")
            protected BigInteger goalsAgainst;

            /**
             * Gets the value of the powerplay property.
             * 
             * @return
             *     possible object is
             *     {@link NetType }
             *     
             */
            public NetType getPowerplay() {
                return powerplay;
            }

            /**
             * Sets the value of the powerplay property.
             * 
             * @param value
             *     allowed object is
             *     {@link NetType }
             *     
             */
            public void setPowerplay(NetType value) {
                this.powerplay = value;
            }

            /**
             * Gets the value of the shorthanded property.
             * 
             * @return
             *     possible object is
             *     {@link NetType }
             *     
             */
            public NetType getShorthanded() {
                return shorthanded;
            }

            /**
             * Sets the value of the shorthanded property.
             * 
             * @param value
             *     allowed object is
             *     {@link NetType }
             *     
             */
            public void setShorthanded(NetType value) {
                this.shorthanded = value;
            }

            /**
             * Gets the value of the evenstrength property.
             * 
             * @return
             *     possible object is
             *     {@link NetType }
             *     
             */
            public NetType getEvenstrength() {
                return evenstrength;
            }

            /**
             * Sets the value of the evenstrength property.
             * 
             * @param value
             *     allowed object is
             *     {@link NetType }
             *     
             */
            public void setEvenstrength(NetType value) {
                this.evenstrength = value;
            }

            /**
             * Gets the value of the shotsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getShotsAgainst() {
                return shotsAgainst;
            }

            /**
             * Sets the value of the shotsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setShotsAgainst(BigInteger value) {
                this.shotsAgainst = value;
            }

            /**
             * Gets the value of the goalsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getGoalsAgainst() {
                return goalsAgainst;
            }

            /**
             * Sets the value of the goalsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setGoalsAgainst(BigInteger value) {
                this.goalsAgainst = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
         *         &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
         *         &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
         *         &lt;element name="penalty" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}goaltendingType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseGoaltendingAttributes"/>
         *       &lt;attribute name="total_shots_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="total_goals_against" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "powerplay",
            "shorthanded",
            "evenstrength",
            "penalty"
        })
        public static class Total {

            protected GoaltendingType powerplay;
            protected GoaltendingType shorthanded;
            protected GoaltendingType evenstrength;
            protected GoaltendingType penalty;
            @XmlAttribute(name = "total_shots_against")
            protected BigInteger totalShotsAgainst;
            @XmlAttribute(name = "total_goals_against")
            protected BigInteger totalGoalsAgainst;
            @XmlAttribute(name = "saves")
            protected BigInteger saves;
            @XmlAttribute(name = "saves_pct")
            protected BigDecimal savesPct;
            @XmlAttribute(name = "shots_against")
            protected BigInteger shotsAgainst;
            @XmlAttribute(name = "goals_against")
            protected BigInteger goalsAgainst;

            /**
             * Gets the value of the powerplay property.
             * 
             * @return
             *     possible object is
             *     {@link GoaltendingType }
             *     
             */
            public GoaltendingType getPowerplay() {
                return powerplay;
            }

            /**
             * Sets the value of the powerplay property.
             * 
             * @param value
             *     allowed object is
             *     {@link GoaltendingType }
             *     
             */
            public void setPowerplay(GoaltendingType value) {
                this.powerplay = value;
            }

            /**
             * Gets the value of the shorthanded property.
             * 
             * @return
             *     possible object is
             *     {@link GoaltendingType }
             *     
             */
            public GoaltendingType getShorthanded() {
                return shorthanded;
            }

            /**
             * Sets the value of the shorthanded property.
             * 
             * @param value
             *     allowed object is
             *     {@link GoaltendingType }
             *     
             */
            public void setShorthanded(GoaltendingType value) {
                this.shorthanded = value;
            }

            /**
             * Gets the value of the evenstrength property.
             * 
             * @return
             *     possible object is
             *     {@link GoaltendingType }
             *     
             */
            public GoaltendingType getEvenstrength() {
                return evenstrength;
            }

            /**
             * Sets the value of the evenstrength property.
             * 
             * @param value
             *     allowed object is
             *     {@link GoaltendingType }
             *     
             */
            public void setEvenstrength(GoaltendingType value) {
                this.evenstrength = value;
            }

            /**
             * Gets the value of the penalty property.
             * 
             * @return
             *     possible object is
             *     {@link GoaltendingType }
             *     
             */
            public GoaltendingType getPenalty() {
                return penalty;
            }

            /**
             * Sets the value of the penalty property.
             * 
             * @param value
             *     allowed object is
             *     {@link GoaltendingType }
             *     
             */
            public void setPenalty(GoaltendingType value) {
                this.penalty = value;
            }

            /**
             * Gets the value of the totalShotsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotalShotsAgainst() {
                return totalShotsAgainst;
            }

            /**
             * Sets the value of the totalShotsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotalShotsAgainst(BigInteger value) {
                this.totalShotsAgainst = value;
            }

            /**
             * Gets the value of the totalGoalsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotalGoalsAgainst() {
                return totalGoalsAgainst;
            }

            /**
             * Sets the value of the totalGoalsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotalGoalsAgainst(BigInteger value) {
                this.totalGoalsAgainst = value;
            }

            /**
             * Gets the value of the saves property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSaves() {
                return saves;
            }

            /**
             * Sets the value of the saves property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSaves(BigInteger value) {
                this.saves = value;
            }

            /**
             * Gets the value of the savesPct property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSavesPct() {
                return savesPct;
            }

            /**
             * Sets the value of the savesPct property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSavesPct(BigDecimal value) {
                this.savesPct = value;
            }

            /**
             * Gets the value of the shotsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getShotsAgainst() {
                return shotsAgainst;
            }

            /**
             * Sets the value of the shotsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setShotsAgainst(BigInteger value) {
                this.shotsAgainst = value;
            }

            /**
             * Gets the value of the goalsAgainst property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getGoalsAgainst() {
                return goalsAgainst;
            }

            /**
             * Sets the value of the goalsAgainst property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setGoalsAgainst(BigInteger value) {
                this.goalsAgainst = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseGoaltendingAttributes"/>
     *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseShootingAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Shootout {

        @XmlAttribute(name = "saves")
        protected BigInteger saves;
        @XmlAttribute(name = "saves_pct")
        protected BigDecimal savesPct;
        @XmlAttribute(name = "shots_against")
        protected BigInteger shotsAgainst;
        @XmlAttribute(name = "goals_against")
        protected BigInteger goalsAgainst;
        @XmlAttribute(name = "goals")
        protected BigInteger goals;
        @XmlAttribute(name = "assists")
        protected BigInteger assists;
        @XmlAttribute(name = "shots")
        protected BigInteger shots;
        @XmlAttribute(name = "missed_shots")
        protected BigInteger missedShots;

        /**
         * Gets the value of the saves property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSaves() {
            return saves;
        }

        /**
         * Sets the value of the saves property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSaves(BigInteger value) {
            this.saves = value;
        }

        /**
         * Gets the value of the savesPct property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSavesPct() {
            return savesPct;
        }

        /**
         * Sets the value of the savesPct property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSavesPct(BigDecimal value) {
            this.savesPct = value;
        }

        /**
         * Gets the value of the shotsAgainst property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getShotsAgainst() {
            return shotsAgainst;
        }

        /**
         * Sets the value of the shotsAgainst property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setShotsAgainst(BigInteger value) {
            this.shotsAgainst = value;
        }

        /**
         * Gets the value of the goalsAgainst property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getGoalsAgainst() {
            return goalsAgainst;
        }

        /**
         * Sets the value of the goalsAgainst property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setGoalsAgainst(BigInteger value) {
            this.goalsAgainst = value;
        }

        /**
         * Gets the value of the goals property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getGoals() {
            return goals;
        }

        /**
         * Sets the value of the goals property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setGoals(BigInteger value) {
            this.goals = value;
        }

        /**
         * Gets the value of the assists property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAssists() {
            return assists;
        }

        /**
         * Sets the value of the assists property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAssists(BigInteger value) {
            this.assists = value;
        }

        /**
         * Gets the value of the shots property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getShots() {
            return shots;
        }

        /**
         * Sets the value of the shots property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setShots(BigInteger value) {
            this.shots = value;
        }

        /**
         * Gets the value of the missedShots property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMissedShots() {
            return missedShots;
        }

        /**
         * Sets the value of the missedShots property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMissedShots(BigInteger value) {
            this.missedShots = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="total" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
     *                   &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
     *                   &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
     *                   &lt;element name="penalty" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseShootingAttributes"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}faceoffAttributes"/>
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseSkaterAttributes"/>
     *                 &lt;attribute name="games_played" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="powerplays" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="team_penalties" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="team_penalty_minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="average" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseAverageSkaterAttributes"/>
     *                 &lt;attribute name="team_penalties" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="team_penalty_minutes" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "total",
        "average"
    })
    public static class Statistics {

        protected TeamRecordType.Statistics.Total total;
        protected TeamRecordType.Statistics.Average average;

        /**
         * Gets the value of the total property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType.Statistics.Total }
         *     
         */
        public TeamRecordType.Statistics.Total getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType.Statistics.Total }
         *     
         */
        public void setTotal(TeamRecordType.Statistics.Total value) {
            this.total = value;
        }

        /**
         * Gets the value of the average property.
         * 
         * @return
         *     possible object is
         *     {@link TeamRecordType.Statistics.Average }
         *     
         */
        public TeamRecordType.Statistics.Average getAverage() {
            return average;
        }

        /**
         * Sets the value of the average property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeamRecordType.Statistics.Average }
         *     
         */
        public void setAverage(TeamRecordType.Statistics.Average value) {
            this.average = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseAverageSkaterAttributes"/>
         *       &lt;attribute name="team_penalties" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="team_penalty_minutes" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Average {

            @XmlAttribute(name = "team_penalties")
            protected BigDecimal teamPenalties;
            @XmlAttribute(name = "team_penalty_minutes")
            protected BigDecimal teamPenaltyMinutes;
            @XmlAttribute(name = "points")
            protected BigDecimal points;
            @XmlAttribute(name = "blocked_att")
            protected BigDecimal blockedAtt;
            @XmlAttribute(name = "assists")
            protected BigDecimal assists;
            @XmlAttribute(name = "shots")
            protected BigDecimal shots;
            @XmlAttribute(name = "penalty_minutes")
            protected BigDecimal penaltyMinutes;
            @XmlAttribute(name = "missed_shots")
            protected BigDecimal missedShots;
            @XmlAttribute(name = "takeaways")
            protected BigDecimal takeaways;
            @XmlAttribute(name = "hits")
            protected BigDecimal hits;
            @XmlAttribute(name = "goals")
            protected BigDecimal goals;
            @XmlAttribute(name = "giveaways")
            protected BigDecimal giveaways;
            @XmlAttribute(name = "blocked_shots")
            protected BigDecimal blockedShots;
            @XmlAttribute(name = "penalties")
            protected BigDecimal penalties;

            /**
             * Gets the value of the teamPenalties property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTeamPenalties() {
                return teamPenalties;
            }

            /**
             * Sets the value of the teamPenalties property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTeamPenalties(BigDecimal value) {
                this.teamPenalties = value;
            }

            /**
             * Gets the value of the teamPenaltyMinutes property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTeamPenaltyMinutes() {
                return teamPenaltyMinutes;
            }

            /**
             * Sets the value of the teamPenaltyMinutes property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTeamPenaltyMinutes(BigDecimal value) {
                this.teamPenaltyMinutes = value;
            }

            /**
             * Gets the value of the points property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPoints() {
                return points;
            }

            /**
             * Sets the value of the points property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPoints(BigDecimal value) {
                this.points = value;
            }

            /**
             * Gets the value of the blockedAtt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBlockedAtt() {
                return blockedAtt;
            }

            /**
             * Sets the value of the blockedAtt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBlockedAtt(BigDecimal value) {
                this.blockedAtt = value;
            }

            /**
             * Gets the value of the assists property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAssists() {
                return assists;
            }

            /**
             * Sets the value of the assists property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAssists(BigDecimal value) {
                this.assists = value;
            }

            /**
             * Gets the value of the shots property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getShots() {
                return shots;
            }

            /**
             * Sets the value of the shots property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setShots(BigDecimal value) {
                this.shots = value;
            }

            /**
             * Gets the value of the penaltyMinutes property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPenaltyMinutes() {
                return penaltyMinutes;
            }

            /**
             * Sets the value of the penaltyMinutes property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPenaltyMinutes(BigDecimal value) {
                this.penaltyMinutes = value;
            }

            /**
             * Gets the value of the missedShots property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMissedShots() {
                return missedShots;
            }

            /**
             * Sets the value of the missedShots property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMissedShots(BigDecimal value) {
                this.missedShots = value;
            }

            /**
             * Gets the value of the takeaways property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTakeaways() {
                return takeaways;
            }

            /**
             * Sets the value of the takeaways property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTakeaways(BigDecimal value) {
                this.takeaways = value;
            }

            /**
             * Gets the value of the hits property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getHits() {
                return hits;
            }

            /**
             * Sets the value of the hits property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setHits(BigDecimal value) {
                this.hits = value;
            }

            /**
             * Gets the value of the goals property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getGoals() {
                return goals;
            }

            /**
             * Sets the value of the goals property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setGoals(BigDecimal value) {
                this.goals = value;
            }

            /**
             * Gets the value of the giveaways property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getGiveaways() {
                return giveaways;
            }

            /**
             * Sets the value of the giveaways property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setGiveaways(BigDecimal value) {
                this.giveaways = value;
            }

            /**
             * Gets the value of the blockedShots property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBlockedShots() {
                return blockedShots;
            }

            /**
             * Sets the value of the blockedShots property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBlockedShots(BigDecimal value) {
                this.blockedShots = value;
            }

            /**
             * Gets the value of the penalties property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPenalties() {
                return penalties;
            }

            /**
             * Sets the value of the penalties property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPenalties(BigDecimal value) {
                this.penalties = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="powerplay" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
         *         &lt;element name="shorthanded" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
         *         &lt;element name="evenstrength" type="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}scoringType" minOccurs="0"/>
         *         &lt;element name="penalty" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseShootingAttributes"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}faceoffAttributes"/>
         *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseSkaterAttributes"/>
         *       &lt;attribute name="games_played" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="powerplays" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="team_penalties" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="team_penalty_minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "powerplay",
            "shorthanded",
            "evenstrength",
            "penalty"
        })
        public static class Total {

            protected ScoringType powerplay;
            protected ScoringType shorthanded;
            protected ScoringType evenstrength;
            protected TeamRecordType.Statistics.Total.Penalty penalty;
            @XmlAttribute(name = "games_played")
            protected BigInteger gamesPlayed;
            @XmlAttribute(name = "powerplays")
            protected BigInteger powerplays;
            @XmlAttribute(name = "team_penalties")
            protected BigInteger teamPenalties;
            @XmlAttribute(name = "team_penalty_minutes")
            protected BigInteger teamPenaltyMinutes;
            @XmlAttribute(name = "faceoffs_won")
            protected BigInteger faceoffsWon;
            @XmlAttribute(name = "faceoffs_lost")
            protected BigInteger faceoffsLost;
            @XmlAttribute(name = "faceoffs")
            protected BigInteger faceoffs;
            @XmlAttribute(name = "faceoff_win_pct")
            protected BigDecimal faceoffWinPct;
            @XmlAttribute(name = "penalties")
            protected BigInteger penalties;
            @XmlAttribute(name = "penalty_minutes")
            protected BigInteger penaltyMinutes;
            @XmlAttribute(name = "blocked_att")
            protected BigInteger blockedAtt;
            @XmlAttribute(name = "hits")
            protected BigInteger hits;
            @XmlAttribute(name = "giveaways")
            protected BigInteger giveaways;
            @XmlAttribute(name = "takeaways")
            protected BigInteger takeaways;
            @XmlAttribute(name = "blocked_shots")
            protected BigInteger blockedShots;
            @XmlAttribute(name = "points")
            protected BigInteger points;
            @XmlAttribute(name = "shooting_pct")
            protected BigDecimal shootingPct;
            @XmlAttribute(name = "goals")
            protected BigInteger goals;
            @XmlAttribute(name = "assists")
            protected BigInteger assists;
            @XmlAttribute(name = "shots")
            protected BigInteger shots;
            @XmlAttribute(name = "missed_shots")
            protected BigInteger missedShots;

            /**
             * Gets the value of the powerplay property.
             * 
             * @return
             *     possible object is
             *     {@link ScoringType }
             *     
             */
            public ScoringType getPowerplay() {
                return powerplay;
            }

            /**
             * Sets the value of the powerplay property.
             * 
             * @param value
             *     allowed object is
             *     {@link ScoringType }
             *     
             */
            public void setPowerplay(ScoringType value) {
                this.powerplay = value;
            }

            /**
             * Gets the value of the shorthanded property.
             * 
             * @return
             *     possible object is
             *     {@link ScoringType }
             *     
             */
            public ScoringType getShorthanded() {
                return shorthanded;
            }

            /**
             * Sets the value of the shorthanded property.
             * 
             * @param value
             *     allowed object is
             *     {@link ScoringType }
             *     
             */
            public void setShorthanded(ScoringType value) {
                this.shorthanded = value;
            }

            /**
             * Gets the value of the evenstrength property.
             * 
             * @return
             *     possible object is
             *     {@link ScoringType }
             *     
             */
            public ScoringType getEvenstrength() {
                return evenstrength;
            }

            /**
             * Sets the value of the evenstrength property.
             * 
             * @param value
             *     allowed object is
             *     {@link ScoringType }
             *     
             */
            public void setEvenstrength(ScoringType value) {
                this.evenstrength = value;
            }

            /**
             * Gets the value of the penalty property.
             * 
             * @return
             *     possible object is
             *     {@link TeamRecordType.Statistics.Total.Penalty }
             *     
             */
            public TeamRecordType.Statistics.Total.Penalty getPenalty() {
                return penalty;
            }

            /**
             * Sets the value of the penalty property.
             * 
             * @param value
             *     allowed object is
             *     {@link TeamRecordType.Statistics.Total.Penalty }
             *     
             */
            public void setPenalty(TeamRecordType.Statistics.Total.Penalty value) {
                this.penalty = value;
            }

            /**
             * Gets the value of the gamesPlayed property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getGamesPlayed() {
                return gamesPlayed;
            }

            /**
             * Sets the value of the gamesPlayed property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setGamesPlayed(BigInteger value) {
                this.gamesPlayed = value;
            }

            /**
             * Gets the value of the powerplays property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPowerplays() {
                return powerplays;
            }

            /**
             * Sets the value of the powerplays property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPowerplays(BigInteger value) {
                this.powerplays = value;
            }

            /**
             * Gets the value of the teamPenalties property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTeamPenalties() {
                return teamPenalties;
            }

            /**
             * Sets the value of the teamPenalties property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTeamPenalties(BigInteger value) {
                this.teamPenalties = value;
            }

            /**
             * Gets the value of the teamPenaltyMinutes property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTeamPenaltyMinutes() {
                return teamPenaltyMinutes;
            }

            /**
             * Sets the value of the teamPenaltyMinutes property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTeamPenaltyMinutes(BigInteger value) {
                this.teamPenaltyMinutes = value;
            }

            /**
             * Gets the value of the faceoffsWon property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getFaceoffsWon() {
                return faceoffsWon;
            }

            /**
             * Sets the value of the faceoffsWon property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setFaceoffsWon(BigInteger value) {
                this.faceoffsWon = value;
            }

            /**
             * Gets the value of the faceoffsLost property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getFaceoffsLost() {
                return faceoffsLost;
            }

            /**
             * Sets the value of the faceoffsLost property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setFaceoffsLost(BigInteger value) {
                this.faceoffsLost = value;
            }

            /**
             * Gets the value of the faceoffs property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getFaceoffs() {
                return faceoffs;
            }

            /**
             * Sets the value of the faceoffs property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setFaceoffs(BigInteger value) {
                this.faceoffs = value;
            }

            /**
             * Gets the value of the faceoffWinPct property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getFaceoffWinPct() {
                return faceoffWinPct;
            }

            /**
             * Sets the value of the faceoffWinPct property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setFaceoffWinPct(BigDecimal value) {
                this.faceoffWinPct = value;
            }

            /**
             * Gets the value of the penalties property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPenalties() {
                return penalties;
            }

            /**
             * Sets the value of the penalties property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPenalties(BigInteger value) {
                this.penalties = value;
            }

            /**
             * Gets the value of the penaltyMinutes property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPenaltyMinutes() {
                return penaltyMinutes;
            }

            /**
             * Sets the value of the penaltyMinutes property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPenaltyMinutes(BigInteger value) {
                this.penaltyMinutes = value;
            }

            /**
             * Gets the value of the blockedAtt property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBlockedAtt() {
                return blockedAtt;
            }

            /**
             * Sets the value of the blockedAtt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBlockedAtt(BigInteger value) {
                this.blockedAtt = value;
            }

            /**
             * Gets the value of the hits property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getHits() {
                return hits;
            }

            /**
             * Sets the value of the hits property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setHits(BigInteger value) {
                this.hits = value;
            }

            /**
             * Gets the value of the giveaways property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getGiveaways() {
                return giveaways;
            }

            /**
             * Sets the value of the giveaways property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setGiveaways(BigInteger value) {
                this.giveaways = value;
            }

            /**
             * Gets the value of the takeaways property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTakeaways() {
                return takeaways;
            }

            /**
             * Sets the value of the takeaways property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTakeaways(BigInteger value) {
                this.takeaways = value;
            }

            /**
             * Gets the value of the blockedShots property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBlockedShots() {
                return blockedShots;
            }

            /**
             * Sets the value of the blockedShots property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBlockedShots(BigInteger value) {
                this.blockedShots = value;
            }

            /**
             * Gets the value of the points property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPoints() {
                return points;
            }

            /**
             * Sets the value of the points property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPoints(BigInteger value) {
                this.points = value;
            }

            /**
             * Gets the value of the shootingPct property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getShootingPct() {
                return shootingPct;
            }

            /**
             * Sets the value of the shootingPct property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setShootingPct(BigDecimal value) {
                this.shootingPct = value;
            }

            /**
             * Gets the value of the goals property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getGoals() {
                return goals;
            }

            /**
             * Sets the value of the goals property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setGoals(BigInteger value) {
                this.goals = value;
            }

            /**
             * Gets the value of the assists property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAssists() {
                return assists;
            }

            /**
             * Sets the value of the assists property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAssists(BigInteger value) {
                this.assists = value;
            }

            /**
             * Gets the value of the shots property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getShots() {
                return shots;
            }

            /**
             * Sets the value of the shots property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setShots(BigInteger value) {
                this.shots = value;
            }

            /**
             * Gets the value of the missedShots property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMissedShots() {
                return missedShots;
            }

            /**
             * Sets the value of the missedShots property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMissedShots(BigInteger value) {
                this.missedShots = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/statistics-v2.0.xsd}baseShootingAttributes"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Penalty {

                @XmlAttribute(name = "goals")
                protected BigInteger goals;
                @XmlAttribute(name = "assists")
                protected BigInteger assists;
                @XmlAttribute(name = "shots")
                protected BigInteger shots;
                @XmlAttribute(name = "missed_shots")
                protected BigInteger missedShots;

                /**
                 * Gets the value of the goals property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getGoals() {
                    return goals;
                }

                /**
                 * Sets the value of the goals property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setGoals(BigInteger value) {
                    this.goals = value;
                }

                /**
                 * Gets the value of the assists property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getAssists() {
                    return assists;
                }

                /**
                 * Sets the value of the assists property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setAssists(BigInteger value) {
                    this.assists = value;
                }

                /**
                 * Gets the value of the shots property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getShots() {
                    return shots;
                }

                /**
                 * Sets the value of the shots property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setShots(BigInteger value) {
                    this.shots = value;
                }

                /**
                 * Gets the value of the missedShots property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMissedShots() {
                    return missedShots;
                }

                /**
                 * Sets the value of the missedShots property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMissedShots(BigInteger value) {
                    this.missedShots = value;
                }

            }

        }

    }

}
