//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:46:38 PM CET 
//


package com.delices.datastore.jaxb.playbyplay;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.delices.datastore.jaxb.playbyplay package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Game_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "game");
    private final static QName _EventTypeStatisticsFaceoff_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "faceoff");
    private final static QName _EventTypeStatisticsShot_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "shot");
    private final static QName _EventTypeStatisticsEmptynetgoal_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "emptynetgoal");
    private final static QName _EventTypeStatisticsBlock_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "block");
    private final static QName _EventTypeStatisticsAssist_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "assist");
    private final static QName _EventTypeStatisticsAttemptblocked_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "attemptblocked");
    private final static QName _EventTypeStatisticsTakeaway_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "takeaway");
    private final static QName _EventTypeStatisticsGiveaway_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "giveaway");
    private final static QName _EventTypeStatisticsPenalty_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "penalty");
    private final static QName _EventTypeStatisticsShotmissed_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "shotmissed");
    private final static QName _EventTypeStatisticsHit_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "hit");
    private final static QName _EventTypeStatisticsShotagainst_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "shotagainst");
    private final static QName _EventTypeStatisticsPowerplay_QNAME = new QName("http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", "powerplay");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.delices.datastore.jaxb.playbyplay
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link EventType.Statistics }
     * 
     */
    public EventType.Statistics createEventTypeStatistics() {
        return new EventType.Statistics();
    }

    /**
     * Create an instance of {@link StatisticsType }
     * 
     */
    public StatisticsType createStatisticsType() {
        return new StatisticsType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link GameType }
     * 
     */
    public GameType createGameType() {
        return new GameType();
    }

    /**
     * Create an instance of {@link DraftType }
     * 
     */
    public DraftType createDraftType() {
        return new DraftType();
    }

    /**
     * Create an instance of {@link VenueType }
     * 
     */
    public VenueType createVenueType() {
        return new VenueType();
    }

    /**
     * Create an instance of {@link ScoringType }
     * 
     */
    public ScoringType createScoringType() {
        return new ScoringType();
    }

    /**
     * Create an instance of {@link InjuryType }
     * 
     */
    public InjuryType createInjuryType() {
        return new InjuryType();
    }

    /**
     * Create an instance of {@link TeamScoringType }
     * 
     */
    public TeamScoringType createTeamScoringType() {
        return new TeamScoringType();
    }

    /**
     * Create an instance of {@link PeriodScoreType }
     * 
     */
    public PeriodScoreType createPeriodScoreType() {
        return new PeriodScoreType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link EventType.Attribution }
     * 
     */
    public EventType.Attribution createEventTypeAttribution() {
        return new EventType.Attribution();
    }

    /**
     * Create an instance of {@link EventType.Location }
     * 
     */
    public EventType.Location createEventTypeLocation() {
        return new EventType.Location();
    }

    /**
     * Create an instance of {@link EventType.Statistics.Faceoff }
     * 
     */
    public EventType.Statistics.Faceoff createEventTypeStatisticsFaceoff() {
        return new EventType.Statistics.Faceoff();
    }

    /**
     * Create an instance of {@link EventType.Statistics.Shot }
     * 
     */
    public EventType.Statistics.Shot createEventTypeStatisticsShot() {
        return new EventType.Statistics.Shot();
    }

    /**
     * Create an instance of {@link EventType.Statistics.Shotagainst }
     * 
     */
    public EventType.Statistics.Shotagainst createEventTypeStatisticsShotagainst() {
        return new EventType.Statistics.Shotagainst();
    }

    /**
     * Create an instance of {@link EventType.Statistics.Shotmissed }
     * 
     */
    public EventType.Statistics.Shotmissed createEventTypeStatisticsShotmissed() {
        return new EventType.Statistics.Shotmissed();
    }

    /**
     * Create an instance of {@link EventType.Statistics.Penalty }
     * 
     */
    public EventType.Statistics.Penalty createEventTypeStatisticsPenalty() {
        return new EventType.Statistics.Penalty();
    }

    /**
     * Create an instance of {@link StatisticsType.Team }
     * 
     */
    public StatisticsType.Team createStatisticsTypeTeam() {
        return new StatisticsType.Team();
    }

    /**
     * Create an instance of {@link StatisticsType.Player }
     * 
     */
    public StatisticsType.Player createStatisticsTypePlayer() {
        return new StatisticsType.Player();
    }

    /**
     * Create an instance of {@link PeriodType.Events }
     * 
     */
    public PeriodType.Events createPeriodTypeEvents() {
        return new PeriodType.Events();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "game")
    public JAXBElement<GameType> createGame(GameType value) {
        return new JAXBElement<GameType>(_Game_QNAME, GameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType.Statistics.Faceoff }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "faceoff", scope = EventType.Statistics.class)
    public JAXBElement<EventType.Statistics.Faceoff> createEventTypeStatisticsFaceoff(EventType.Statistics.Faceoff value) {
        return new JAXBElement<EventType.Statistics.Faceoff>(_EventTypeStatisticsFaceoff_QNAME, EventType.Statistics.Faceoff.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType.Statistics.Shot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "shot", scope = EventType.Statistics.class)
    public JAXBElement<EventType.Statistics.Shot> createEventTypeStatisticsShot(EventType.Statistics.Shot value) {
        return new JAXBElement<EventType.Statistics.Shot>(_EventTypeStatisticsShot_QNAME, EventType.Statistics.Shot.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "emptynetgoal", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsEmptynetgoal(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsEmptynetgoal_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "block", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsBlock(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsBlock_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "assist", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsAssist(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsAssist_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "attemptblocked", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsAttemptblocked(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsAttemptblocked_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "takeaway", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsTakeaway(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsTakeaway_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "giveaway", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsGiveaway(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsGiveaway_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType.Statistics.Penalty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "penalty", scope = EventType.Statistics.class)
    public JAXBElement<EventType.Statistics.Penalty> createEventTypeStatisticsPenalty(EventType.Statistics.Penalty value) {
        return new JAXBElement<EventType.Statistics.Penalty>(_EventTypeStatisticsPenalty_QNAME, EventType.Statistics.Penalty.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType.Statistics.Shotmissed }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "shotmissed", scope = EventType.Statistics.class)
    public JAXBElement<EventType.Statistics.Shotmissed> createEventTypeStatisticsShotmissed(EventType.Statistics.Shotmissed value) {
        return new JAXBElement<EventType.Statistics.Shotmissed>(_EventTypeStatisticsShotmissed_QNAME, EventType.Statistics.Shotmissed.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "hit", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsHit(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsHit_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType.Statistics.Shotagainst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "shotagainst", scope = EventType.Statistics.class)
    public JAXBElement<EventType.Statistics.Shotagainst> createEventTypeStatisticsShotagainst(EventType.Statistics.Shotagainst value) {
        return new JAXBElement<EventType.Statistics.Shotagainst>(_EventTypeStatisticsShotagainst_QNAME, EventType.Statistics.Shotagainst.class, EventType.Statistics.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feed.elasticstats.com/schema/hockey/pbp-v2.0.xsd", name = "powerplay", scope = EventType.Statistics.class)
    public JAXBElement<StatisticsType> createEventTypeStatisticsPowerplay(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_EventTypeStatisticsPowerplay_QNAME, StatisticsType.class, EventType.Statistics.class, value);
    }

}
