//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:46:58 PM CET 
//


package com.delices.datastore.jaxb.schedule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for gameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="venue" type="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}venueType" minOccurs="0"/>
 *         &lt;element name="home" type="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}participantType"/>
 *         &lt;element name="away" type="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}participantType"/>
 *         &lt;element name="broadcast" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="network" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="satellite" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="radio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="internet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}baseGameAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gameType", propOrder = {
    "venue",
    "home",
    "away",
    "broadcast"
})
public class GameType {

    protected VenueType venue;
    @XmlElement(required = true)
    protected ParticipantType home;
    @XmlElement(required = true)
    protected ParticipantType away;
    protected GameType.Broadcast broadcast;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "coverage")
    protected String coverage;
    @XmlAttribute(name = "away_team")
    protected String awayTeam;
    @XmlAttribute(name = "home_team")
    protected String homeTeam;
    @XmlAttribute(name = "scheduled")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduled;

    /**
     * Gets the value of the venue property.
     * 
     * @return
     *     possible object is
     *     {@link VenueType }
     *     
     */
    public VenueType getVenue() {
        return venue;
    }

    /**
     * Sets the value of the venue property.
     * 
     * @param value
     *     allowed object is
     *     {@link VenueType }
     *     
     */
    public void setVenue(VenueType value) {
        this.venue = value;
    }

    /**
     * Gets the value of the home property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantType }
     *     
     */
    public ParticipantType getHome() {
        return home;
    }

    /**
     * Sets the value of the home property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantType }
     *     
     */
    public void setHome(ParticipantType value) {
        this.home = value;
    }

    /**
     * Gets the value of the away property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantType }
     *     
     */
    public ParticipantType getAway() {
        return away;
    }

    /**
     * Sets the value of the away property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantType }
     *     
     */
    public void setAway(ParticipantType value) {
        this.away = value;
    }

    /**
     * Gets the value of the broadcast property.
     * 
     * @return
     *     possible object is
     *     {@link GameType.Broadcast }
     *     
     */
    public GameType.Broadcast getBroadcast() {
        return broadcast;
    }

    /**
     * Sets the value of the broadcast property.
     * 
     * @param value
     *     allowed object is
     *     {@link GameType.Broadcast }
     *     
     */
    public void setBroadcast(GameType.Broadcast value) {
        this.broadcast = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverage(String value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the awayTeam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwayTeam() {
        return awayTeam;
    }

    /**
     * Sets the value of the awayTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwayTeam(String value) {
        this.awayTeam = value;
    }

    /**
     * Gets the value of the homeTeam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeTeam() {
        return homeTeam;
    }

    /**
     * Sets the value of the homeTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeTeam(String value) {
        this.homeTeam = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduled() {
        return scheduled;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduled(XMLGregorianCalendar value) {
        this.scheduled = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="network" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="satellite" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cable" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="radio" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="internet" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Broadcast {

        @XmlAttribute(name = "network")
        protected String network;
        @XmlAttribute(name = "satellite")
        protected String satellite;
        @XmlAttribute(name = "cable")
        protected String cable;
        @XmlAttribute(name = "radio")
        protected String radio;
        @XmlAttribute(name = "internet")
        protected String internet;

        /**
         * Gets the value of the network property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetwork() {
            return network;
        }

        /**
         * Sets the value of the network property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetwork(String value) {
            this.network = value;
        }

        /**
         * Gets the value of the satellite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSatellite() {
            return satellite;
        }

        /**
         * Sets the value of the satellite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSatellite(String value) {
            this.satellite = value;
        }

        /**
         * Gets the value of the cable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCable() {
            return cable;
        }

        /**
         * Sets the value of the cable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCable(String value) {
            this.cable = value;
        }

        /**
         * Gets the value of the radio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRadio() {
            return radio;
        }

        /**
         * Sets the value of the radio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRadio(String value) {
            this.radio = value;
        }

        /**
         * Gets the value of the internet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternet() {
            return internet;
        }

        /**
         * Sets the value of the internet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternet(String value) {
            this.internet = value;
        }

    }

}
