//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 07:46:58 PM CET 
//


package com.delices.datastore.jaxb.schedule;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for participantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="participantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}baseGameAttributes"/>
 *                 &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}outcomeAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seed" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="rotation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "participantType", propOrder = {
    "source"
})
public class ParticipantType {

    protected ParticipantType.Source source;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "alias")
    protected String alias;
    @XmlAttribute(name = "seed")
    protected BigInteger seed;
    @XmlAttribute(name = "rotation")
    protected String rotation;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantType.Source }
     *     
     */
    public ParticipantType.Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantType.Source }
     *     
     */
    public void setSource(ParticipantType.Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the seed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeed() {
        return seed;
    }

    /**
     * Sets the value of the seed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeed(BigInteger value) {
        this.seed = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotation(String value) {
        this.rotation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}baseGameAttributes"/>
     *       &lt;attGroup ref="{http://feed.elasticstats.com/schema/hockey/schedule-v2.0.xsd}outcomeAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Source {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "title")
        protected String title;
        @XmlAttribute(name = "status")
        protected String status;
        @XmlAttribute(name = "coverage")
        protected String coverage;
        @XmlAttribute(name = "away_team")
        protected String awayTeam;
        @XmlAttribute(name = "home_team")
        protected String homeTeam;
        @XmlAttribute(name = "scheduled")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar scheduled;
        @XmlAttribute(name = "outcome")
        protected String outcome;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the coverage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoverage() {
            return coverage;
        }

        /**
         * Sets the value of the coverage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoverage(String value) {
            this.coverage = value;
        }

        /**
         * Gets the value of the awayTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeam() {
            return awayTeam;
        }

        /**
         * Sets the value of the awayTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeam(String value) {
            this.awayTeam = value;
        }

        /**
         * Gets the value of the homeTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeam() {
            return homeTeam;
        }

        /**
         * Sets the value of the homeTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeam(String value) {
            this.homeTeam = value;
        }

        /**
         * Gets the value of the scheduled property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getScheduled() {
            return scheduled;
        }

        /**
         * Sets the value of the scheduled property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setScheduled(XMLGregorianCalendar value) {
            this.scheduled = value;
        }

        /**
         * Gets the value of the outcome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutcome() {
            return outcome;
        }

        /**
         * Sets the value of the outcome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutcome(String value) {
            this.outcome = value;
        }

    }

}
